### ISSUE TITLE
US01 Frontend - Registro de usuarios

### ISSUE THREAD

**Issue by Jdvd01** [Jdvd01/c18-46-t-java-react#10]
**Criterio de Aceptación**
**Comprador**
1. Acceso Inmediato al Catálogo: Los usuarios pueden acceder al catálogo de libros y comenzar a explorar sin necesidad de registrarse en el sistema.
2. Navegación Completa sin Restricciones: Los usuarios pueden navegar por todas las secciones del sitio, incluyendo la página de inicio, las categorías de libros, la página de detalles del libro, etc., sin ser redirigidos a una página de registro en ningún momento.
3. Visualización Completa de los Libros: Los usuarios pueden ver detalles completos de los libros, como título, autor, sinopsis, precio, calificaciones y reseñas, sin necesidad de registrarse previamente.
4. Función de Búsqueda Disponible: La función de búsqueda está disponible y accesible para los usuarios no registrados, lo que les permite buscar libros específicos por título, autor, género, etc.
5. Añadir al Carrito sin Registro: Los usuarios pueden añadir libros al carrito de compras sin necesidad de registrarse previamente, lo que les permite recopilar los libros deseados antes de decidir si desean crear una cuenta.
6. Opción de Registro en Cualquier Momento: En cualquier punto durante la navegación o el proceso de compra, se proporciona una opción clara y visible para que los usuarios se registren si lo desean, sin interrumpir su experiencia actual.

**Vendedor**

1. Proceso de Registro Obligatorio: Los vendedores deben completar obligatoriamente el proceso de registro en el sistema antes de poder listar y vender sus libros.
2. Acceso Limitado sin Registro: Los vendedores no pueden acceder a las funciones de venta y gestión de libros sin haber completado previamente el registro en el sistema.
3. Formulario de Registro Completo: El formulario de registro solicita información completa y relevante de los vendedores, incluyendo detalles como nombre, dirección, información de contacto y detalles de pago para recibir pagos de las ventas.
4. Aprobación del Registro: Después de completar el registro, el sistema verifica y aprueba la cuenta del vendedor antes de permitirle listar libros y realizar ventas.
5. Acceso a Funciones de Venta Después del Registro: Una vez aprobado el registro, los vendedores tienen acceso completo a las funciones de venta, como listar libros, establecer precios, gestionar inventario y procesar pedidos.
6. Cumplimiento de Términos y Condiciones: Los vendedores deben aceptar los términos y condiciones del sitio antes de completar el registro, garantizando su comprensión y cumplimiento de las políticas establecidas.
7. Actualización de Información de Registro: Los vendedores pueden actualizar su información de registro en cualquier momento, como cambiar la dirección de envío o actualizar los detalles de pago, para mantener su cuenta actualizada y precisa.

**US**
Como Usuario quiero registrarme dentro del sistema para poder ingresar y empezar a comprar y/o vender libros.

**Comment by Jdvd01** [comment]
Listos los estilos de login y registro, @quserforgitp se va a encargar de la funcionalidad

**Comment by quserforgitp** [comment]
## Funcionalidad agregada
